init:
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- ps: Update-AppveyorBuild -Message "Image '$env:APPVEYOR_BUILD_WORKER_IMAGE'@'$env:APPVEYOR_BUILD_WORKER_CLOUD' cloud. $env:APPVEYOR_REPO_COMMIT_MESSAGE"

clone_folder: $(HOME)/foo/bar/foobar

test_script:
- sh: ls -ltra $HOME
- sh: ls -ltra $HOME/foo
- sh: CLONEROOTFILES="$(find $HOME/foo -user root)"
- sh: if [[ -n "$CLONEROOTFILES" ]]; then echo "Found root owned files in clone folder!"; echo -n "$CLONEROOTFILES"; echo; return 1; fi

build: off
